# Insurance ABAC Demo Configuration

databricks_profile: "DEFAULT"
warehouse_id: "862f1d757f0424f7"
catalog: "apscat"
schema: "insurance"

sql_files:
  - "0.1insurance_abac_functions.sql"
  - "0.2insurance_database_schema.sql"
  - "0.3insurance_extended_tables.sql"
  - "6.TestInsuranceData_Simple.sql"

